version: "3.8"
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
      - sqlite:/app/sqlite
    ports:
      - 8000:80
volumes:
  sqlite: